### ISSUE TITLE
End Ores not spawning in End biomes outside Enderdragon island

### ISSUE THREAD

**Issue by TelepathicGrunt** [Lothrazar/ElementaryOres#1]
I noticed with you mod, that the end ores only spawn in the "the_end" biome and not in the "small_end_islands", "end_barrens", "end_midlands", and end_highland" biomes. I don't know if this was intentional but if not, I am just letting you know so you can add your ores to all the end biomes. :)

**Comment by Lothrazar** [comment]
1.15 is  abandoned by all the mod devs and pack makers. fixed in 1.16 https://www.curseforge.com/minecraft/mc-mods/elementary-ores/files/3390855
