### ISSUE TITLE
Possible Conflict or Mod Crash in 1.15.1

### ISSUE THREAD

**Issue by Camawama** [Lothrazar/ElementaryOres#3]
Hey there, my name is Alex and I have been trying to put together this Modpack for me and some friends to play on. Your mod works perfectly fine client-side but when running on a server it crashes and doesn't even load the world (like a few other mods I tried installing. I have put together a ZIP file with the Logs, Crash report (if there is one), and the other mods installed with it. I did this for every mod that caused the server to crash and I am contacting developers of the mods in hopes that it's enough information to diagnose the problems. I love to discover bugs and report them so if you ever need some help my discord is Cama#6274

Forge Version: Forge-30.0.39
Minecraft Version: 1.15.1

Here is the link: http://www.mediafire.com/file/zwad5fufypk1s2d/Elementary_Ores.zip/file

**Comment by jrjespersen** [comment]
I also get a crash when trying to add this mod to a server:

Crash log: https://pastebin.com/h04mEeid
Minecraft version: 1.15.1
Forge Version: forge-1.15.1-30.0.51
No other mods were loaded.

**Comment by Lothrazar** [comment]
1.15 is  abandoned by all the mod devs and pack makers. fixed in 1.16 https://www.curseforge.com/minecraft/mc-mods/elementary-ores/files/3390855
