### ISSUE TITLE
[1.15.2] Server crash on start

### ISSUE THREAD

**Issue by kwpugh** [Lothrazar/ElementaryOres#5]
Crashes at start on dedicated server.

Report: https://gist.github.com/kwpugh/da886a70accb603fac05250442095730

Mod: ElementaryOres-1.15.2-1.0.0.jar

Forge: net.minecraftforge:31.1.0

**Comment by SDUBZ** [comment]
same crash 
[crash-2020-02-21_21.06.59-server.txt](https://github.com/Lothrazar/elementary-ores/files/4235603/crash-2020-02-21_21.06.59-server.txt)

**Comment by dreckz** [comment]
I'm getting the same crash as well
[crash-2020-03-24_16.03.22-server.txt](https://github.com/Lothrazar/elementary-ores/files/4377669/crash-2020-03-24_16.03.22-server.txt)

**Comment by Lothrazar** [comment]
1.15 is  abandoned by all the mod devs and pack makers. fixed in 1.16 https://www.curseforge.com/minecraft/mc-mods/elementary-ores/files/3390855
